db:
  enabled: true
  image:
    repository: supabase/postgres
    tag: "latest"
  environment:
    POSTGRES_PASSWORD: example123456
  
# Studio Application
studio:
  environment:
    SUPABASE_URL: http://api.localhost
    SUPABASE_REST_URL: http://api.localhost/rest/v1/
    STUDIO_PG_META_URL: http://demo-supabase-kong.default.svc.cluster.local:8000/pg
    SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTY0MDMwMDQwMCwiZXhwIjoxNzk4MDY2ODAwfQ.JaEiRNdyxX3Pk6XupxauDazXeadLTgTHz5cV7joUrQE"
    SUPABASE_SERVICE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNjQwMzAwNDAwLCJleHAiOjE3OTgwNjY4MDB9.sUJPVrhMsSaLgizyCWIgNOIRmjavxDB4Lm3hzb4dC5U"
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    tls:
      - secretName: studio.localhost
        hosts:
          - studio.localhost
    hosts:
      - host: studio.localhost
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: api
              servicePort: 3000

# Auth Service
auth:
  dbConnectionSecrets:
    enabled: false
    secretName: mysecret
  environment:
    DB_HOST: demo-supabase-db.default.svc.cluster.local
    DB_PORT: "5432"
    DB_DRIVER: postgres
    DB_NAME: postgres
    DB_USER: postgres
    DB_PASSWORD: example123456
    DB_SSL: allow
    GOTRUE_API_HOST: "0.0.0.0"
    GOTRUE_API_PORT: "9999"
    GOTRUE_SITE_URL: http://studio.localhost
    GOTRUE_URI_ALLOW_LIST: "*"
    GOTRUE_DISABLE_SIGNUP: "false"
    GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
    GOTRUE_JWT_ADMIN_ROLES: service_role
    GOTRUE_JWT_AUD: authenticated
    GOTRUE_JWT_SECRET: "abcdefghijklmnopqrstuvwxyz123456"
    GOTRUE_JWT_EXP: "3600"
    GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
    GOTRUE_MAILER_AUTOCONFIRM: "true"
    GOTRUE_SMTP_ADMIN_EMAIL: "your-mail@example.com"
    GOTRUE_SMTP_HOST: "smtp.example.com"
    GOTRUE_SMTP_PORT: "587"
    GOTRUE_SMTP_USER: "your-mail@example.com"
    GOTRUE_SMTP_PASS: "example123456"
    GOTRUE_SMTP_SENDER_NAME: "your-mail@example.com"
    GOTRUE_EXTERNAL_PHONE_ENABLED: "false"
    GOTRUE_SMS_AUTOCONFIRM: "false"
    GOTRUE_MAILER_URLPATHS_INVITE: "http://api.localhost/auth/v1/verify"
    GOTRUE_MAILER_URLPATHS_CONFIRMATION: "http://api.localhost/auth/v1/verify"
    GOTRUE_MAILER_URLPATHS_RECOVERY: "http://api.localhost/auth/v1/verify"
    GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: "http://api.localhost/auth/v1/verify"

# Rest Service
rest:
  dbConnectionSecrets:
    enabled: false
    secretName: mysecret
  environment:
    DB_HOST: demo-supabase-db.default.svc.cluster.local
    DB_PORT: "5432"
    DB_DRIVER: posstgres
    DB_NAME: postgres
    DB_USER: postgres
    DB_PASSWORD: example123456
    DB_SSL: allow
    PGRST_DB_SCHEMA: public,storage
    PGRST_DB_ANON_ROLE: anon
    PGRST_JWT_SECRET: "abcdefghijklmnopqrstuvwxyz123456"
    PGRST_DB_USE_LEGACY_GUCS: "false"

# Realtime Service
realtime:
  dbConnectionSecrets:
    enabled: false
    secretName: mysecret
  environment:
    DB_HOST: demo-supabase-db.default.svc.cluster.local
    DB_PORT: "5432"
    DB_NAME: postgres
    DB_USER: postgres
    DB_PASSWORD: example123456
    DB_SSL: "false"
    JWT_SECRET: "abcdefghijklmnopqrstuvwxyz123456"
    PORT: "4000"
    REPLICATION_MODE: RLS
    REPLICATION_POLL_INTERVAL: "100"
    SECURE_CHANNELS: "true"
    SLOT_NAME: supabase_realtime_rls
    TEMPORARY_SLOT: "true"

# Meta Service
meta:
  dbConnectionSecrets:
    enabled: false
    secretName: mysecret
  environment:
    DB_HOST: demo-supabase-db.default.svc.cluster.local
    DB_PORT: "5432"
    DB_DRIVER: postgres
    DB_NAME: postgres
    DB_USER: postgres
    DB_PASSWORD: example123456
    DB_SSL: disable
    PG_META_PORT: "8080"

# Storage Service
storage:
  dbConnectionSecrets:
    enabled: false
    secretName: mysecret
  environment:
    DB_HOST: demo-supabase-db.default.svc.cluster.local
    DB_PORT: "5432"
    DB_DRIVER: postgres
    DB_NAME: postgres
    DB_USER: postgres
    DB_PASSWORD: example123456
    DB_SSL: allow
    ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTY0MDMwMDQwMCwiZXhwIjoxNzk4MDY2ODAwfQ.JaEiRNdyxX3Pk6XupxauDazXeadLTgTHz5cV7joUrQE"
    SERVICE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNjQwMzAwNDAwLCJleHAiOjE3OTgwNjY4MDB9.sUJPVrhMsSaLgizyCWIgNOIRmjavxDB4Lm3hzb4dC5U"
    POSTGREST_URL: http://demo-supabase-rest.default.svc.cluster.local:3000
    PGRST_JWT_SECRET: "abcdefghijklmnopqrstuvwxyz123456"
    PGOPTIONS: -c search_path=storage,public
    FILE_SIZE_LIMIT: '52428800'
    STORAGE_BACKEND: file
    FILE_STORAGE_BACKEND_PATH: /var/lib/storage
    TENANT_ID: stub
    REGION: stub
    GLOBAL_S3_BUCKET: stub

# Kong
kong:
  environment:
    KONG_DATABASE: "off"
    KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
    KONG_DNS_ORDER: LAST,A,CNAME
    KONG_PLUGINS: request-transformer,cors,key-auth,acl
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    tls:
      - secretName: api.localhost
        hosts:
          - api.localhost
    hosts:
      - host: api.localhost
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: api
              servicePort: 80
  credentials:
    anonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTY0MDMwMDQwMCwiZXhwIjoxNzk4MDY2ODAwfQ.JaEiRNdyxX3Pk6XupxauDazXeadLTgTHz5cV7joUrQE"
    serviceRoleKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNjQwMzAwNDAwLCJleHAiOjE3OTgwNjY4MDB9.sUJPVrhMsSaLgizyCWIgNOIRmjavxDB4Lm3hzb4dC5U"